# Generated by Django 3.2 on 2023-09-28 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('url', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='page_viewer/static/images/propfirmlogo')),
                ('blog_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prop_firm',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop_firm.category')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_ids', models.CharField(max_length=300)),
                ('answer_ids', models.CharField(max_length=300)),
                ('prop_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop_firm.propfirm')),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('prop_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop_firm.propfirm')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop_firm.questions')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
